
services:
  - type: web
    name: yunks-contract-checker
    env: docker
    plan: free

    envVars:
      - key: PRODUCTION
        value: "true"
      - key: TELEGRAM_BOT_TOKEN
        value: "7843191744:AAFTgk1EKhgahjaKuDGtBh-r73ndpCDHeFs"
      - key: WEBHOOK_BASE_URL
        value: "https://yunks-contract-checker.onrender.com"
