
services:
  - type: web
    name: yunks-contract-checker
    env: docker
    plan: free
    healthCheckPath: /

    envVars:
      - key: PRODUCTION
        value: "true"
      - key: TELEGRAM_BOT_TOKEN
        value: "8478896729:AAHjParJUsyZkV3GmzBA78wLFQUMQSxAE_E"
      - key: WEBHOOK_BASE_URL
        value: "https://yunks-contract-checker.onrender.com"
