
services:
  - type: web
    name: yunks-contract-checker
    env: docker
    plan: free
    healthCheckPath: /

    envVars:
      - key: PRODUCTION
        value: "true"
      - key: TELEGRAM_BOT_TOKEN
<<<<<<< HEAD
        value: "7843191744:AAFTgk1EKhgahjaKuDGtBh-r73ndpCDHeFs"
=======
        value: "8478896729:AAHjParJUsyZkV3GmzBA78wLFQUMQSxAE_E"
>>>>>>> 74a848e1776a4a4811652093096b6c0d78bd106b
      - key: WEBHOOK_BASE_URL
        value: "https://yunks-contract-checker.onrender.com"
