
services:
  - type: web
    name: yunks-contract-checker
    env: docker
    plan: free
    healthCheckPath: /
    envVars:
      - key: PRODUCTION
        value: "true"
      - key: TELEGRAM_BOT_TOKEN
        value: "7843191744:AAFTgk1EKhgahjaKuDGtBh-r73ndpCDHeFs"
